version: "3.9"

services:
  mosquitto:
    build: ./infra/mosquitto
    container_name: mosquitto
    ports:
      - "8883:8883"   # TLS MQTT
    volumes:
      - ./infra/mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./infra/mosquitto/aclfile:/mosquitto/config/aclfile:ro
      - ./infra/mosquitto/certs:/mosquitto/certs:ro
      - mosquitto_data:/mosquitto/data
      - mosquitto_log:/mosquitto/log
    restart: unless-stopped

  telegraf:
    image: telegraf:1.30
    container_name: telegraf
    depends_on: [mosquitto, influxdb]
    volumes:
      - ./infra/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./infra/mosquitto/certs/ca/ca.crt:/etc/telegraf/ssl/mqtt_ca.crt:ro
      - ./infra/mosquitto/certs/clients/telegraf_bridge/telegraf_bridge.crt:/etc/telegraf/ssl/telegraf.crt:ro
      - ./infra/mosquitto/certs/clients/telegraf_bridge/telegraf_bridge.key:/etc/telegraf/ssl/telegraf.key:ro
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - INFLUXDB_ORG=${INFLUXDB_ORG}
      - INFLUXDB_BUCKET=${INFLUXDB_BUCKET}
    restart: unless-stopped


  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    restart: unless-stopped

  grafana:
    image: grafana/grafana:11.2.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      - ./infra/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASS}
    depends_on: [influxdb]
    restart: unless-stopped

volumes:
  mosquitto_data: {}
  mosquitto_log: {}
  influxdb_data: {}
  grafana_data: {}
